# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: eventos
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080